<a href="https://colab.research.google.com/github/Brunacsc/p/blob/main/Mod7Aula2_Carregando_e_tratando_os_dados.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 0. Índice <a name="Contents"></a>
1. [Importando bibliotecas](#import)
2. [Carregando o dataframe](#read)
5. [Dados duplicados](#duplicados)
3. [Identificando e Tratando dados ausentes/missing](#identificando)
6. [Dados categorizados](#categorizados)
6. [Separando as variáveis explicativas da target](#separando)


# 1. Importando bibliotecas <a name="import"></a>

<div style="text-align: right"
     
[Voltar ao índice](#Contents)

In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns

# 2. Carregando o dataframe <a name="read"></a>
<div style="text-align: right"
     
[Voltar ao índice](#Contents)

In [ ]:
titanic = sns.load_dataset('titanic')
titanic.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [ ]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   survived     891 non-null    int64   
 1   pclass       891 non-null    int64   
 2   sex          891 non-null    object  
 3   age          714 non-null    float64 
 4   sibsp        891 non-null    int64   
 5   parch        891 non-null    int64   
 6   fare         891 non-null    float64 
 7   embarked     889 non-null    object  
 8   class        891 non-null    category
 9   who          891 non-null    object  
 10  adult_male   891 non-null    bool    
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object  
 13  alive        891 non-null    object  
 14  alone        891 non-null    bool    
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.6+ KB


In [ ]:
titanic.dtypes

survived          int64
pclass            int64
sex              object
age             float64
sibsp             int64
parch             int64
fare            float64
embarked         object
class          category
who              object
adult_male         bool
deck           category
embark_town      object
alive            object
alone              bool
dtype: object

# 3. Dados duplicados <a name="duplicados"></a>
<div style="text-align: right"
     
[Voltar ao índice](#Contents)

In [ ]:
titanic.drop_duplicates()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0           0       3    male  22.0      1      0   7.2500        S  Third   
1           1       1  female  38.0      1      0  71.2833        C  First   
2           1       3  female  26.0      0      0   7.9250        S  Third   
3           1       1  female  35.0      1      0  53.1000        S  First   
4           0       3    male  35.0      0      0   8.0500        S  Third   
..        ...     ...     ...   ...    ...    ...      ...      ...    ...   
885         0       3  female  39.0      0      5  29.1250        Q  Third   
887         1       1  female  19.0      0      0  30.0000        S  First   
888         0       3  female   NaN      1      2  23.4500        S  Third   
889         1       1    male  26.0      0      0  30.0000        C  First   
890         0       3    male  32.0      0      0   7.7500        Q  Third   

       who  adult_male deck  embark_town alive  alone  
0      man        True  NaN  Southampton    no  False  
1    woman       False    C    Cherbourg   yes  False  
2    woman       False  NaN  Southampton   yes   True  
3    woman       False    C  Southampton   yes  False  
4      man        True  NaN  Southampton    no   True  
..     ...         ...  ...          ...   ...    ...  
885  woman       False  NaN   Queenstown    no  False  
887  woman       False    B  Southampton   yes   True  
888  woman       False  NaN  Southampton    no  False  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True  

[784 rows x 15 columns]

In [ ]:
titanic.shape

(891, 15)

In [ ]:
titanic = titanic.drop_duplicates()
titanic.shape

(784, 15)

In [ ]:
titanic.tail()

survived  pclass     sex   age  sibsp  parch    fare embarked  class  \
885         0       3  female  39.0      0      5  29.125        Q  Third   
887         1       1  female  19.0      0      0  30.000        S  First   
888         0       3  female   NaN      1      2  23.450        S  Third   
889         1       1    male  26.0      0      0  30.000        C  First   
890         0       3    male  32.0      0      0   7.750        Q  Third   

       who  adult_male deck  embark_town alive  alone  
885  woman       False  NaN   Queenstown    no  False  
887  woman       False    B  Southampton   yes   True  
888  woman       False  NaN  Southampton    no  False  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True

In [ ]:
titanic.reset_index(drop=True, inplace=True)

In [ ]:
titanic.tail()

survived  pclass     sex   age  sibsp  parch    fare embarked  class  \
779         0       3  female  39.0      0      5  29.125        Q  Third   
780         1       1  female  19.0      0      0  30.000        S  First   
781         0       3  female   NaN      1      2  23.450        S  Third   
782         1       1    male  26.0      0      0  30.000        C  First   
783         0       3    male  32.0      0      0   7.750        Q  Third   

       who  adult_male deck  embark_town alive  alone  
779  woman       False  NaN   Queenstown    no  False  
780  woman       False    B  Southampton   yes   True  
781  woman       False  NaN  Southampton    no  False  
782    man        True    C    Cherbourg   yes   True  
783    man        True  NaN   Queenstown    no   True

# 4. Identificando e tratando dados ausentes <a name="identificando"></a>
<div style="text-align: right"
     
[Voltar ao índice](#Contents)

https://scikit-learn.org/stable/modules/tree.html#id2


A árvore de decisão requer pouca preparação de dados. Outras técnicas geralmente requerem normalização de dados, variáveis fictícias precisam ser criadas e valores em branco precisam ser removidos. Observe, entretanto, que **este módulo não oferece suporte a valores ausentes**.

In [ ]:
titanic.isna().sum()

survived         0
pclass           0
sex              0
age            106
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           582
embark_town      2
alive            0
alone            0
dtype: int64

In [ ]:
percentage = (titanic.isnull().sum() / len(titanic)) * 100
percentage

survived        0.000000
pclass          0.000000
sex             0.000000
age            13.520408
sibsp           0.000000
parch           0.000000
fare            0.000000
embarked        0.255102
class           0.000000
who             0.000000
adult_male      0.000000
deck           74.234694
embark_town     0.255102
alive           0.000000
alone           0.000000
dtype: float64

In [ ]:
# dropar todas as colunas que tenha pelo menos 1 NA
titanic_sem_na = titanic.dropna(axis=1)

In [ ]:
titanic_sem_na.head()

survived  pclass     sex  sibsp  parch     fare  class    who  adult_male  \
0         0       3    male      1      0   7.2500  Third    man        True   
1         1       1  female      1      0  71.2833  First  woman       False   
2         1       3  female      0      0   7.9250  Third  woman       False   
3         1       1  female      1      0  53.1000  First  woman       False   
4         0       3    male      0      0   8.0500  Third    man        True   

  alive  alone  
0    no  False  
1   yes  False  
2   yes   True  
3   yes  False  
4    no   True

In [ ]:
titanic_sem_na.shape

(784, 11)

In [ ]:
titanic_sem_na.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 784 entries, 0 to 783
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype   
---  ------      --------------  -----   
 0   survived    784 non-null    int64   
 1   pclass      784 non-null    int64   
 2   sex         784 non-null    object  
 3   sibsp       784 non-null    int64   
 4   parch       784 non-null    int64   
 5   fare        784 non-null    float64 
 6   class       784 non-null    category
 7   who         784 non-null    object  
 8   adult_male  784 non-null    bool    
 9   alive       784 non-null    object  
 10  alone       784 non-null    bool    
dtypes: bool(2), category(1), float64(1), int64(4), object(3)
memory usage: 51.5+ KB


# 5. Dados categorizados <a name="categorizados"></a>
<div style="text-align: right"
     
[Voltar ao índice](#Contents)

https://scikit-learn.org/stable/modules/tree.html#id2

CART (árvores de classificação e regressão) é muito semelhante a C4.5, mas difere porque oferece suporte a variáveis ​​de destino numéricas (regressão) e não calcula conjuntos de regras. A CART constrói árvores binárias usando o recurso e o limite que geram o maior ganho de informação em cada nó.

scikit-learn usa uma versão otimizada do algoritmo CART; entretanto, a **implementação do scikit-learn não suporta variáveis categorizadas** por enquanto.

In [ ]:
titanic_sem_na.head(2)

survived  pclass     sex  sibsp  parch     fare  class    who  adult_male  \
0         0       3    male      1      0   7.2500  Third    man        True   
1         1       1  female      1      0  71.2833  First  woman       False   

  alive  alone  
0    no  False  
1   yes  False

- **survived** - se o passageiro sobreviveu ou não, ou seja, nossa target
- **pclass** - classe em que o passageiro estava (primeira, segunda, terceira)
- **sex** - genero do passageiro (masculino ou feminino)
- **sibsp** - quantidade de irmãos/esposos/esposas no navio (0 a 8)
- **parch** - quantidade de pais/filhos a bordo
- **fare** - preço do ticket
- **class** - igual a pclass
- **who** - se é homem, mulher ou criança
- **adult_male** - se é um homem adulto
- **alive** - igual a survived
- **alone** - se estava sozinho a bordo


## Survived e alive


In [ ]:
titanic_sem_na.survived.value_counts()

0    461
1    323
Name: survived, dtype: int64

In [ ]:
titanic_sem_na.survived.value_counts(normalize=True)

0    0.58801
1    0.41199
Name: survived, dtype: float64

In [ ]:
titanic_sem_na.alive.value_counts()

no     461
yes    323
Name: alive, dtype: int64

In [ ]:
titanic_sem_na[['alive','survived','sibsp']].groupby(['alive','survived']).count()

sibsp
alive survived       
no    0           461
yes   1           323

In [ ]:
titanic_sem_na = titanic_sem_na.drop('alive',axis=1)

## pclass e class

In [ ]:
titanic_sem_na['pclass'].unique()

array([3, 1, 2], dtype=int64)

In [ ]:
titanic_sem_na['class'].unique()

['Third', 'First', 'Second']
Categories (3, object): ['Third', 'First', 'Second']

In [ ]:
titanic_sem_na[['pclass','class','sibsp']].groupby(['pclass','class']).count()

sibsp
pclass class        
1      First   214.0
       Second    NaN
       Third     NaN
2      First     NaN
       Second  165.0
       Third     NaN
3      First     NaN
       Second    NaN
       Third   405.0

In [ ]:
titanic_sem_na = titanic_sem_na.drop('pclass',axis=1)

## Outras variáveis

In [ ]:
titanic_sem_na['sex'].unique()

array(['male', 'female'], dtype=object)

In [ ]:
titanic_sem_na['sibsp'].unique()

array([1, 0, 3, 4, 2, 5, 8], dtype=int64)

In [ ]:
titanic_sem_na['parch'].unique()

array([0, 1, 2, 5, 3, 4, 6], dtype=int64)

In [ ]:
titanic_sem_na['who'].unique()

array(['man', 'woman', 'child'], dtype=object)

In [ ]:
titanic_sem_na[['sex','who','sibsp']].groupby(['sex','who']).count()

sibsp
sex    who         
female child     42
       woman    251
male   child     40
       man      451

In [ ]:
titanic_sem_na.head(2)

survived     sex  sibsp  parch     fare  class    who  adult_male  alone
0         0    male      1      0   7.2500  Third    man        True  False
1         1  female      1      0  71.2833  First  woman       False  False

## Transformando em dummie (flag)

In [ ]:
# titanic_encoded = titanic_sem_na.copy()
titanic_encoded = pd.get_dummies(titanic_sem_na, columns=['class','who'], drop_first=True)
titanic_encoded.head(20)

survived     sex  sibsp  parch     fare  adult_male  alone  class_Second  \
0          0    male      1      0   7.2500        True  False             0   
1          1  female      1      0  71.2833       False  False             0   
2          1  female      0      0   7.9250       False   True             0   
3          1  female      1      0  53.1000       False  False             0   
4          0    male      0      0   8.0500        True   True             0   
5          0    male      0      0   8.4583        True   True             0   
6          0    male      0      0  51.8625        True   True             0   
7          0    male      3      1  21.0750       False  False             0   
8          1  female      0      2  11.1333       False  False             0   
9          1  female      1      0  30.0708       False  False             1   
10         1  female      1      1  16.7000       False  False             0   
11         1  female      0      0  26.5500       False   True             0   
12         0    male      0      0   8.0500        True   True             0   
13         0    male      1      5  31.2750        True  False             0   
14         0  female      0      0   7.8542       False   True             0   
15         1  female      0      0  16.0000       False   True             1   
16         0    male      4      1  29.1250       False  False             0   
17         1    male      0      0  13.0000        True   True             1   
18         0  female      1      0  18.0000       False  False             0   
19         1  female      0      0   7.2250       False   True             0   

    class_Third  who_man  who_woman  
0             1        1          0  
1             0        0          1  
2             1        0          1  
3             0        0          1  
4             1        1          0  
5             1        1          0  
6             0        1          0  
7             1        0          0  
8             1        0          1  
9             0        0          0  
10            1        0          0  
11            0        0          1  
12            1        1          0  
13            1        1          0  
14            1        0          0  
15            0        0          1  
16            1        0          0  
17            0        1          0  
18            1        0          1  
19            1        0          1

## Mapping

In [ ]:
titanic_encoded.sex.unique()

array(['male', 'female'], dtype=object)

In [ ]:
titanic_encoded.sex = titanic_encoded.sex.map({'female': 1, 'male':0})

In [ ]:
titanic_encoded.sex.unique()

array([0, 1], dtype=int64)

## Mudando alguns tipos de dados

In [ ]:
titanic_encoded.dtypes

survived          int64
sex               int64
sibsp             int64
parch             int64
fare            float64
adult_male         bool
alone              bool
class_Second      uint8
class_Third       uint8
who_man           uint8
who_woman         uint8
dtype: object

In [ ]:
titanic_encoded.adult_male.astype(int)

0      1
1      0
2      0
3      0
4      1
      ..
779    0
780    0
781    0
782    1
783    1
Name: adult_male, Length: 784, dtype: int32

In [ ]:
titanic_encoded.adult_male = titanic_encoded.adult_male.astype(int)
titanic_encoded.alone = titanic_encoded.alone.astype(int)

In [ ]:
titanic_encoded.dtypes

survived          int64
sex               int64
sibsp             int64
parch             int64
fare            float64
adult_male        int32
alone             int32
class_Second      uint8
class_Third       uint8
who_man           uint8
who_woman         uint8
dtype: object

In [ ]:
titanic_encoded.columns

Index(['survived', 'sex', 'sibsp', 'parch', 'fare', 'adult_male', 'alone',
       'class_Second', 'class_Third', 'who_man', 'who_woman'],
      dtype='object')

# 6. Separando as variáveis explicativas da target <a name="separando"></a>
<div style="text-align: right"
     
[Voltar ao índice](#Contents)

In [ ]:
titanic_encoded


survived  sex  sibsp  parch     fare  adult_male  alone  class_Second  \
0           0    0      1      0   7.2500           1      0             0   
1           1    1      1      0  71.2833           0      0             0   
2           1    1      0      0   7.9250           0      1             0   
3           1    1      1      0  53.1000           0      0             0   
4           0    0      0      0   8.0500           1      1             0   
..        ...  ...    ...    ...      ...         ...    ...           ...   
779         0    1      0      5  29.1250           0      0             0   
780         1    1      0      0  30.0000           0      1             0   
781         0    1      1      2  23.4500           0      0             0   
782         1    0      0      0  30.0000           1      1             0   
783         0    0      0      0   7.7500           1      1             0   

     class_Third  who_man  who_woman  
0              1        1          0  
1              0        0          1  
2              1        0          1  
3              0        0          1  
4              1        1          0  
..           ...      ...        ...  
779            1        0          1  
780            0        0          1  
781            1        0          1  
782            0        1          0  
783            1        1          0  

[784 rows x 11 columns]

In [ ]:
y = titanic_encoded.survived

In [ ]:
y

0      0
1      1
2      1
3      1
4      0
      ..
779    0
780    1
781    0
782    1
783    0
Name: survived, Length: 784, dtype: int64

In [ ]:
X = titanic_encoded.drop('survived',axis=1)